### ISSUE TITLE
Interested In [Artisans]

### ISSUE THREAD

**Issue by JohnsonMasino** [MichealCodez/awesome-project-ideas#2]
# Project Name:
Artisan.

## Inspiration:
I like the idea for this project and the problem it is trying to solve.
And I'll feel good to have contributed to this project.

## Tech Stack:
Django.

## What Will I Work On?
I want to work on the API authentication system.

## Any More Comments ?
I want to start working on the authentication system for this project.
I want to write the APIs with Django.

## My Questions ?
How would the admin want this project files structure(paths) to look like ?
Once I know this, I'll know how to place my files and all that but if it is my choice then I can start working on it as soon as possible.

**Comment by MichealCodez** [comment]
That’s awesome 👏🏾 

so this is it
Inside the Artisan’s folder 
Start a Django project called backend 
Inside the backend folder start an app called authentication

then go ahead with your thing
Don’t forget to always include readme in every folder explaining what’s the folder is about 

for now continue the PR to this repo as the project grows bigger we will have a separate repo for it.

Good luck Johnson

**Comment by JohnsonMasino** [comment]
Okay cool.
On it.
I wanted to introduce an idea but I figured we make a move on the one we have at hand at least.

**Comment by MichealCodez** [comment]
Go ahead with dropping the project idea too

we will like to have it up
Someone else might be interested in that instead

**Comment by JohnsonMasino** [comment]
Okay cool.
Got it
