### ISSUE TITLE
Adding Google Authentication to Artisan.

### ISSUE THREAD

**Issue by JohnsonMasino** [MichealCodez/awesome-project-ideas#4]
# Artisans

I want to be adding features to the artisans backend and I want to implement authentication using google this time around.

**Comment by MichealCodez** [comment]
Good Idea!

Go for it✊🏾

**Comment by JohnsonMasino** [comment]
Okay cool. I'll be on it.

**Comment by JohnsonMasino** [comment]
I was wondering, is there a way you test these codes before merging to the master branch ? Or should we hold a code review session before you merge so we test out the codes ? I'll show you how they work.

**Comment by JohnsonMasino** [comment]
I have added and tested the google authentication system and have created a pull request for it.

**Comment by MichealCodez** [comment]
> I was wondering, is there a way you test these codes before merging to the master branch ? Or should we hold a code review session before you merge so we test out the codes ? I'll show you how they work.

Don't worry just make sure you test it and provide good comments and updated readme, I will pull your code and go through them all when I'm free

**Comment by MichealCodez** [comment]
> I have added and tested the google authentication system and have created a pull request for it.

Yeah, I made a comment on it

**Comment by JohnsonMasino** [comment]
Okay cool.
